
################################################################################
# This script converts the count tables that are generated by umi tools
# Original format is long list with gene, cell, count in a long list.
# but I want a table which is gene (rows) x cells (columns), with counts as values.
#
# Also, I'd like to add the gene names.

library(reshape2)
library(stringr)

################################################################################
# Directories

base_dir = '/Users/m.wehrens/Data/2022_09_micetimeline/Analysis.v01/'
data_dir = '/Users/m.wehrens/Data/2022_09_micetimeline/test_libraries/counttables/'
# data_dir = '/Users/m.wehrens/Data/2022_09_micetimeline/test_libraries/ERCC/mapping_ERCC/'

################################################################################
# Set up data files

mousetime_ids = 
    c(  testSet10Cycles='Martijn-Wehrens-library-test-mice-10cycles_AAC3KK3M5_S21_L001_pT.nonRibo_E99_Aligned.out.counts.tsv',
        testSet12Cycles='Martijn-Wehrens-library-test-mice-12cycles_AAC3KK3M5_S22_L001_pT.nonRibo_E99_Aligned.out.counts.tsv',
        testSet10Cycles_rawcnt = 'Martijn-Wehrens-library-test-mice-10cycles_AAC3KK3M5_S21_L001_pT.counts-raw.tsv',
        testSet12Cycles_rawcnt = 'Martijn-Wehrens-library-test-mice-12cycles_AAC3KK3M5_S22_L001_pT.counts-raw.tsv')
# mousetime_ids = 
#     c(  ERCC_testSet10Cycles='ERCC_Martijn-Wehrens-library-test-mice-10cycles_AAC3KK3M5_S21_L001_pT.nonRibo_E99_Aligned.out.counts.tsv',
#         ERCC_testSet12Cycles='ERCC_Martijn-Wehrens-library-test-mice-12cycles_AAC3KK3M5_S22_L001_pT.nonRibo_E99_Aligned.out.counts.tsv')
dataset_list_paths_mousetime = paste0(data_dir, mousetime_ids)
names(dataset_list_paths_mousetime) = names(mousetime_ids)

################################################################################
# Obtain gene symbols with ensemble IDs
        
if (file.exists(paste0(base_dir,'Rdata/ens_to_sym_conv_table__107_mouse.Rdata'))) {
    
    # Load the table if it was created and saved before
    print('Loading existing ens->name conversion table.')
    load(paste0(base_dir,'Rdata/ens_to_sym_conv_table__107_mouse.Rdata'))
    
} else {
    
    stop('Conversion table ensembl ID and symbol not found.')
    
}

# Note: very few names are double, see 
# freq_names=table(names(ens_to_sym_conv_table__XX_mouse))
# freq_names[freq_names>1]
# ens_to_sym_conv_table__XX_mouse[names(ens_to_sym_conv_table__XX_mouse) %in% names(freq_names[freq_names>1])]
# Seems to be mostly inconsequential genes
# ENSG00000276085 ENSG00000276085 ENSG00000277796 ENSG00000277796 ENSG00000230417 ENSG00000230417 ENSG00000277768 ENSG00000277768 ENSG00000277336 ENSG00000277336 
#        "CCL3L3"        "CCL3L1"        "CCL3L3"        "CCL3L1"     "LINC00856"     "LINC00595"        "CCL3L3"        "CCL3L1"        "CCL3L3"        "CCL3L1" 
# ENSG00000276700 ENSG00000276700 ENSG00000276700 ENSG00000276700 ENSG00000277739 ENSG00000277739 ENSG00000277739 ENSG00000277739 ENSG00000275757 ENSG00000275757 
#     "RNA5-8SN4"     "RNA5-8SN3"     "RNA5-8SN2"     "RNA5-8SN1"     "RNA5-8SN4"     "RNA5-8SN3"     "RNA5-8SN2"     "RNA5-8SN1"     "RNA5-8SN4"     "RNA5-8SN3" 
# ENSG00000275757 ENSG00000275757 ENSG00000274917 ENSG00000274917 ENSG00000274917 ENSG00000274917 ENSG00000274917 ENSG00000273730 ENSG00000273730 ENSG00000273730 
#     "RNA5-8SN2"     "RNA5-8SN1"     "RNA5-8SN5"     "RNA5-8SN4"     "RNA5-8SN3"     "RNA5-8SN2"     "RNA5-8SN1"     "RNA5-8SN4"     "RNA5-8SN3"     "RNA5-8SN2" 
# ENSG00000273730 ENSG00000207062 ENSG00000207062 ENSG00000206785 ENSG00000206785 ENSG00000278233 ENSG00000278233 ENSG00000278233 ENSG00000278233 ENSG00000275215 
#     "RNA5-8SN1"    "SNORA15B-2"    "SNORA15B-1"    "SNORA15B-2"    "SNORA15B-1"     "RNA5-8SN4"     "RNA5-8SN3"     "RNA5-8SN2"     "RNA5-8SN1"     "RNA5-8SN4" 
# ENSG00000275215 ENSG00000275215 ENSG00000275215 ENSG00000278189 ENSG00000278189 ENSG00000278189 ENSG00000278189 ENSG00000283889 ENSG00000283889 
#     "RNA5-8SN3"     "RNA5-8SN2"     "RNA5-8SN1"     "RNA5-8SN4"     "RNA5-8SN3"     "RNA5-8SN2"     "RNA5-8SN1"       "KIR3DS1"      "KIR2DL5A" 


#rownames(dataTable1_df)
#ens_to_sym_conv_table__XX_mouse[rownames(dataTable1_df)]
# show how many gene symbols are redundant
#length(unique(ens_to_sym_conv_table__XX_mouse[unique(dataTable1$gene)]))/length(unique(dataTable1$gene))

################################################################################
# Conversion

for (idx in 1:length(dataset_list_paths_mousetime)) {
    
    current_path = dataset_list_paths_mousetime[idx]
    
    # current_path =  dataset_list_paths_mousetime[1]
    # current_path =  dataset_list_paths_mousetime[2]
    # current_path =  dataset_list_paths_mousetime[3]
    # current_path =  dataset_list_paths_mousetime[4]

    # Load the table
    current_data_table=NA; current_data_df=NA # just to prevent mix-ups
    current_data_table=
        read.table(current_path, header = 1)
    current_data_table=current_data_table[order(current_data_table$cell),]
    
    # Convert to gene x cell matrix (data frame)
    current_data_df=
        acast(current_data_table, gene~cell, value.var="count")
    current_data_df[is.na(current_data_df)]=0
    
    # Update rownames and colnames
    # Add gene name to ensembl ID
    rownames(current_data_df)=paste0(rownames(current_data_df),':',ens_to_sym_conv_table__XX_mouse[rownames(current_data_df)])
    colnames(current_data_df)=paste0('X',sprintf("%03d", as.numeric(colnames(current_data_df))))

    
    # Write the table
    write.table(x = current_data_df,file = gsub(pattern = 'counts', replacement = 'counts.table', x = current_path), row.names = T, col.names = T, quote = F)
    
}




